stages:
  – build
  – deploy

image: alpine

before_script:
  – git config –global http.sslVerify false

get_packer:
  stage: build
  artifacts:
    paths:
    – packer
  script:
    – echo "Fetching packer"
    – wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    – unzip packer_1.5.5_linux_amd64.zip
    – chmod +x packer

deploy:
  stage: deploy
  script:
    – echo "Building Packer Image"
    – cd server-image
    – ../packer build -force techtest.pkr.hcl
